# Site settings
name: Elsie
email: Elisehanchenhoste@gmail.com
url: https://elsiepelsie.github.io/
description: "A blog and a portfolio"
author: "author"
title: "Elsiepelsie"
permalink: pretty
baseurl: ""

# social
github:
  username: username

twitter:
  username: username